version: '3.8'

services:
  admin-backend:
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    volumes:
      - ./admin-backend:/usr/src/app
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    command: sh -c "npm install && tail -f /dev/null"  # Mantém o container rodando para edição

  user-backend:
    build:
      context: ./user-backend
      dockerfile: Dockerfile
    volumes:
      - ./user-backend:/usr/src/app
    ports:
      - '3002:3002'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    command: sh -c "npm install && tail -f /dev/null"  # Mantém o container rodando para edição

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
