version: "3.7"
services:
  admin-backend:
    build:
      context: ./admin-backend
      target: development
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://adminuser:securepassword@db:5432/admin_db
      SERVER_PORT: 8081
    volumes:
      - ./admin-backend:/app
      - ../prisma:/app/prisma
      - node_modules_admin:/app/node_modules

  user-backend:
    build:
      context: ./user-backend
      target: development
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://useruser:securepassword@db:5432/user_db
      SERVER_PORT: 8080
    volumes:
      - ./user-backend:/app
      - ../prisma:/app/prisma
      - node_modules_user:/app/node_modules

  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "adminuser"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: securepassword
    expose:
      - "5432"

volumes:
  postgres-data:
  node_modules_admin:
  node_modules_user:
