FROM node:20 AS base

# Instala git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean

WORKDIR /usr/src

# Instala as dependências de desenvolvimento, se necessário

COPY admin-backend/package*.json /usr/src/admin-backend/
COPY user-backend/package*.json /usr/src/user-backend/

RUN cd /usr/src/admin-backend && npm install
RUN cd /usr/src/user-backend && npm install

CMD ["sh", "-c", "tail -f /dev/null"]  # Mantém o container rodando para edição
