FROM node:20 AS base

# Instala git
RUN apk update && \
    apk add --no-cache git

WORKDIR /usr/src

# Instala as dependências de desenvolvimento, se necessário
COPY admin-backend/package*.json /usr/src/admin-backend/
COPY user-backend/package*.json /usr/src/user-backend/

RUN cd /usr/src/admin-backend && npm install
RUN cd /usr/src/user-backend && npm install

EXPOSE 3003  # Se precisar de uma porta para algum serviço de edição

CMD ["sh", "-c", "tail -f /dev/null"]  # Mantém o container rodando para edição
